export const GET_HOSPITALS_SEARCH_REQUEST = 'GET_HOSPITALS_SEARCH_REQUEST';
export const GET_HOSPITALS_SEARCH_SUCCESS = 'GET_HOSPITALS_SEARCH_SUCCESS';
export const GET_HOSPITALS_SEARCH_FAILURE = 'GET_HOSPITALS_SEARCH_FAILURE';

export const GET_HOSPITAL_DETAILS_REQUEST = 'GET_HOSPITAL_DETAILS_REQUEST';
export const GET_HOSPITAL_DETAILS_SUCCESS = 'GET_HOSPITAL_DETAILS_SUCCESS';
export const GET_HOSPITAL_DETAILS_FAILURE = 'GET_HOSPITAL_DETAILS_FAILURE';
