export const SEND_CONTACT_MAIL_REQUEST = 'SEND_CONTACT_MAIL_REQUEST';
export const SEND_CONTACT_MAIL_SUCCESS = 'SEND_CONTACT_MAIL_SUCCESS';
export const SEND_CONTACT_MAIL_FAILURE = 'SEND_CONTACT_MAIL_FAILURE';

export const HIDE_FORM_STATUS_MESSAGE = 'HIDE_FORM_STATUS_MESSAGE';
