export const SEND_DOCZO_APP_MAIL_REQUEST = 'SEND_DOCZO_APP_MAIL_REQUEST';
export const SEND_DOCZO_APP_MAIL_SUCCSS = 'SEND_DOCZO_APP_MAIL_SUCCSS';
export const SEND_DOCZO_APP_MAIL_FAILURE = 'SEND_DOCZO_APP_MAIL_FAILURE';

export const HIDE_FORM_STATUS_MESSAGE = 'HIDE_FORM_STATUS_MESSAGE';
