export const GET_ALL_SPECIALITIES_LIST_REQUEST =
  'GET_ALL_SPECIALITIES_LIST_REQUEST';
export const GET_ALL_SPECIALITIES_LIST_SUCCESS =
  'GET_ALL_SPECIALITIES_LIST_SUCCESS';
export const GET_ALL_SPECIALITIES_LIST_FAILURE =
  'GET_ALL_SPECIALITIES_LIST_FAILURE';
